CREATE DATABASE IF NOT EXISTS db_task4;
USE db_task4;

CREATE TABLE IF NOT EXISTS tbl_quotes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quote TEXT NOT NULL,
    author VARCHAR(255) NOT NULL,
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
